version: "3.9"
services:
  app:
    build: .
    image: eat_fe_image
    container_name: eat_fe_app
    command: yarn dev
    ports:
      - "${VITE_PORT}:5180"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - eat_fe_net

  nginx:
    image: nginx:1.22.1-alpine
    container_name: eat_fe_nginx
    restart: unless-stopped
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - NGINX_HOST=${NGINX_HOST}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./docker/nginx:/etc/nginx/templates
    depends_on:
      - app
    networks:
      - eat_fe_net

networks:
  eat_fe_net:
    name: eat_fe_net
    driver: bridge
